### ISSUE TITLE
Breaks forms which rely on named submit buttons

### ISSUE THREAD

**Issue by Danita** [Woopra/browser-tracker#1]
I know that the documentation explicitly states "Note: Do not set name for any inputs/buttons to the following: “submit”, “method”, “length”", but this renders Woopra unusable when forms rely on named buttons for functionality such as prev/next page or such, as the buttons don't get sent to the server.

It's a pity because it's such a great product. And expensive too. Thanks!

**Comment by billyvg** [comment]
Hey @Danita, could you drop a message to our support team (support@woopra.com) -- we'll be able to help you out better there.  Thank you!

**Comment by Danita** [comment]
Thanks, but what is this repo for, then?
