### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by rpellerin** [Woopra/browser-tracker#4]
Hi,
Could this be published to NPM please?
Thank you

**Comment by tyscorp** [comment]
I published `@woopra/browser-tracker@5.2.0-beta.0`.

Usage:

```js
import Tracker from '@woopra/browser-tracker/src/tracker';

const woopra = new Tracker();

woopra.config(...)
woopra.track(...);
```

The src directory is not currently transpiled so you'll need to configure your bundler to do it. There is a plan to provide a separate transpiled bundle for usage with modules.

The package does not work in node.js.
